### ISSUE TITLE
Deeplinking ne radi - 404 - HTML5 PushState, nginx.conf 

### ISSUE THREAD

**Issue by kernel-memory-dump** [igr/appoint.one#45]
Da bi Deep-Linkovanje radilo  pri upotrebi HTML5 Push-State routing-a 
Trebali bi izmeniti nginx.conf da vraca index.html kao 404 page, da bi se app uspešno inicijalizovala.
Npr trenutno  linkovanjem direktno na home, dobijamo 404 posto naravno nepostoji /home  ili
/home.index.html fajl
https://appoint-one.herokuapp.com/home

http://prntscr.com/rycodo

**Comment by kernel-memory-dump** [comment]
Suštinski env replace ako se pusti da zameni location / za našim + error 404 direktivu iz default config-a treba pregaziti  

error_page  404  /index.html;

**Comment by igr** [comment]
Hvala! Inače, ne koristimo više Herokua

**Comment by igr** [comment]
Hvala, ovo zatvaram jer nismo na Heroku više
